### ISSUE TITLE
Use XDG standards.

### ISSUE THREAD

**Issue by Jookia** [Tox-Archive/Tox-STS#40]
Rather than saying Tox lives in ~/.config, it should follow the XDG standard: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html Like with APPDATA this allows hijacking environmental variables to make portable versions.

So instead of:
``The path for Tox save file on Linux is ~/.config/tox/tox_save``

It should be:
``The path for Tox save file on Linux is $XDG_CONFIG_HOME/tox/tox_save. If $XDG_CONFIG_HOME is not set, $HOME/.config/tox/tox_save should be used.``

**Comment by zetok** [comment]
@Jookia could you please make a proposal? There are now [simple steps for it defined](https://github.com/Tox/Tox-STS/blob/master/Submitting%20proposals.md), so that it shouldn't be hard to do it, right? `;)`

**Comment by Jookia** [comment]
I'm sorry, I don't have the time to do that.
