### ISSUE TITLE
Port from Tox_Client_Guidelines

### ISSUE THREAD

**Issue by zetok** [Tox-Archive/Tox-STS#58]
Things from https://github.com/irungentoo/Tox_Client_Guidelines needs to be "ported" to STS.

List tracking progress below:
- [x] [Tox_Client_Guidelines/Required/Bootstrapping.md](https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Required/Bootstrapping.md) - #65
- [x] [Tox_Client_Guidelines/Important/Avatars.md](https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Important/Avatars.md) - #52
- [ ] [Tox_Client_Guidelines/Important/File_Transfers.md](https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Important/File_Transfers.md)    ←–-merge together
- [ ] [Tox_Client_Guidelines/Suggestions/Resuming.md](https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Suggestions/Resuming.md)        ←–/

~~- [ ] [Tox_Client_Guidelines/Suggestions/Theme_support.md](https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Suggestions/Theme_support.md)~~

Items from Client Guidelines that are not listed are already a part of STS.

**Comment by zetok** [comment]
Do clients have to have a standardised support for "Themes" ?

**Comment by Impyy** [comment]
@zetok With standardized support you mean that one theme can be applied to multiple clients?

**Comment by zetok** [comment]
@Impyy not really.. that was just in regard to copypasting ~verbatim what's in ``Tox_Client_Guidelines``, which basically says that client might have a support for "themes". Doesn't really seem useful to me, but…

As for whether multiple clients should look the same, it's a separate question for which, if there is a need, separate issue should be opened.

**Comment by dvor** [comment]
The client *might* have a support for "themes" or *might not*. I don't think that it should be part of STS at all. It won't affect any functions of Tox, it won't affect other clients.

**Comment by ProMcTagonist** [comment]
Theme support should not be in the STS. Clients may lean KDE or elementary and still have good UX and interoperability.

**Comment by zetok** [comment]
ok, then I'm crossing porting it out

**Comment by GrayHatter** [comment]
I'll echo @dvor on this one, themes is a stylistic choice, and the STS should do NOTHING about stylistic choices except when to state that clients expect A to display differently from B. E.g. clients should display images sent as "inline" to display differently from "saveable" .
