### ISSUE TITLE
support for retroactive message editing if any should be in STS not in the core

### ISSUE THREAD

**Issue by x368** [Tox-Archive/Tox-STS#73]
Editability of sent messages after the fact is asked for in https://github.com/irungentoo/toxcore/issues/1418

I am arguing that (https://github.com/irungentoo/toxcore/issues/1418#issuecomment-139881711)

> no changes in toxcore are necesary to fully implement the desired functionality in a safe, inexpensive and a non-intrusive fashion. Hence this belongs to STS not here.

 and illustrate by a hypothetical approach: https://github.com/irungentoo/toxcore/issues/1418#issuecomment-139792358

> reserving a certain string in the beginning of the message (to indicate the "to be interpreted" mode), the actual command and the decimal relative number backwards (-1, -2 and so on) followed by the line delimiter and then the new version of the message.
> 
> Like
> 
>     Take the bus 2344
>     
>     ///edit -1
>     Take the bus 234

**Comment by GrayHatter** [comment]
:-1: 

STS is meant to help interoperability, not to enforce bad design policies. This would be required of clients in order to not break standard messaging.

**Comment by x368** [comment]
> STS is meant to help interoperability, not to enforce bad design policies.

Would you be more specific about what is the "bad" design policy and _why_ it is bad?

> This would be required of clients in order to not break standard messaging.

What you are referring to by "this"?

My proposal does not require any change in the existing clients, unless a client wants to implement a new UI feature "sending modification messages" (which the users otherwise can do by hand as soon as the specification defines the format) or another new UI feature "fancy visualization of the modification messages from the remote parties" (which the users do not necessarily need, the modifications messages can be quite usable if shown as-is).

It is not the example specification which I am lobbying for, the goal is a reliable design.

Which is better, to put retroactive editing into STS or into the core API?

This means, which is a better prerequisite for security, debugging, amount of code, maintainability, interoperability, extendability, something else? Why?

Let us present arguments, not only opinions. My arguments are in https://github.com/irungentoo/toxcore/issues/1418. May be I should copy them here for completeness.

**Comment by GrayHatter** [comment]
I'll cite plenty of guidelines, are best practices. If you can get anyone
else to agree with you on the point that; "showing code like messages to
the user will not dissuade adoption". Tox is supposed to replace Skype. If
any client chooses not to follow this standard, they'll never get a strong
user base outside any such niche. Adding this to the STS forces clients to
support this. It'd be non optional. Everything in the STS can me ignored,
and the client will still function normally.

You're suggesting we put a special use case on messages. So instead of just
displaying messages,  clients now HAVE to parse them for content.

**Comment by x368** [comment]
> "showing code like messages to the user will not dissuade adoption"

You are talking about UI, while I am talking about separating protocols and implementations.

> You're suggesting we put a special use case on messages.

True. And I believe I am aware of the implications. If you see a scenario where this really breaks something (interoperability, security, reliability?) I appreciate to be told about it.

It does not provide a nice UI _if the client does not bother about the specification_, but it guarantees _some_ coherent presentation even in this case.

> So instead of just displaying messages, clients now HAVE to parse them for content.

This is the very opposite of what I wrote in the proposal, do I have to re-cite myself to make the point?

**Comment by GrayHatter** [comment]
You've only opened an issue, there's no proposed changes listed only an
idea for how it could be handled. And your idea breaks the UI for any
client that doesn't support this implementation. Again, no other section
breaks the UI if you ignore it.

I could start using the action type message to send/receive meta data, but
that would make every user of any other client hate me.

**Comment by x368** [comment]
I can not agree with many of your comments but this may depend on our interpretation of each other's thoughts. We are thinking in different contexts and thanks for your efforts to find mutual understanding.

I would like to isolate the new functionality (past message correction) from the current core protocol. 

On the other side this may be not very important - if all current users are supposed to upgrade as soon as toxcore changes. This will not be the case when there are alternative Tox core protocol implementations but for the moment we have that extra freedom to break backward compatibility.

My [proposal](https://github.com/irungentoo/toxcore/issues/1418#issuecomment-139792358) was motivated by ensuring full backward compatibility and this of course comes with some costs (I have to be by own opponent, for clarity).

* the _encoding_ of the modifications and the corresponding _visualization_ are to coincide in corner cases (this would happen when the clients do not interpret the messages at all); this allows full compatibility with the current core protocol, leaving it untouched; nevertheless this choice is a compromise

* the semantics of the user input inevitably changes (subtly, but inevitably) - the user must be aware that some rare sequences of characters may lead to different visualization ("editing of other messages") on the receiving side than verbatim; not very intrusive but negative anyway

A possible cleaner solution would be to add a message metainformation field to the core protocol (and then naturally to the toxcore API). Say, if a message has zero in this meta field than the client is not supposed to do anything extra. If the field has a number, the client is supposed to somehow visualize replacement of the contents of the message _the-number_ messages ago (surely, show the new contents even if the receiving user does not allow to overwrite/hide the old one).

Does this sound acceptable from your perspective? Then indeed this issue belongs to toxcore even though STS possibly should mention _how_ the clients preferably visualize retroactive editions.
